#!/bin/bash
# +----------------------------------------------------------------------------+
# | XMMEEC-remote v0.3 * Remote scripts for XMMEEC application                 |
# | Copyright (C) 2019-2022 Pozsár Zsolt <pozsar.zsolt@szerafingomba.hu>       |
# | xmmeec-getoverride                                                         |
# | Get override status from remote computer                                   |
# +----------------------------------------------------------------------------+
#
#   This program is free software: you can redistribute it and/or modify it
# under the terms of the European Union Public License 1.1 version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.

# Exit codes:
#   0: normal exit
#   1: command line parameter is missing
#   2: directory of override files is missing

STAT=("neutral" "neutral" "neutral" "neutral")

searchvarlibdirectory()
{
  VARLIBDIR="/var/lib/$1"
  if [ ! -d $VARLIBDIR ]
  then
    VARLIBDIR="/var/local/lib/$1"
    if [ ! -d $VARLIBDIR ]
    then
      exit 2
    fi
  fi
}

getoverride()
{
  if [ $1 == 'mm3d' ] || [ $1 == 'mm5d' ]
  then
    for I in `seq 1 4`;
    do
      if [ -f $VARLIBDIR/out$I ]
      then
        STAT[$I]=`cat $VARLIBDIR/out$I`
      else
        STAT[$I]="neutral"
      fi
      echo ${STAT[$I]}
    done
  fi
  if [ $1 == 'mm8d' ]
  then
    for I in `seq 1 3`;
    do
      if [ -f $VARLIBDIR/$2/out$I ]
      then
        STAT[$I]=`cat $VARLIBDIR/$2/out$I`
      else
        STAT[$I]="neutral"
      fi
      echo ${STAT[$I]}
    done
  fi
}

usage()
{
  echo "Usage:"
  echo "    $0 type channel"
  echo "    $0 mm3d|mm5d|mm8d 0..8"
  echo ""
}

# main function
if [ $# -lt 2 ];
then
  usage
  exit 1
fi
searchvarlibdirectory $1
getoverride $1 $2
exit 0
