#!/bin/sh
set -e
if [ "$1" = "configure" ]; then
  if [ -d /usr/doc -a ! -e /usr/doc/xmmeec-remote -a -d /usr/share/doc/xmmeec-remote ]; then
    ln -sf /usr/share/doc/xmmeec-remote /usr/doc/xmmeec-remote
  fi
fi
